<h1>Form</h1>
<form action="/result" method="get">
  <label for="city">City:</label>
  <input type="text" id="city" name="city"><br><br>
  <label for="zipcode">Zipcode:</label>
  <input type="text" id="zipcode" name="zipcode"><br><br>
  <label for="cusine">Cuisine:</label>
  <input type="text" id="cuisine" name="cuisine"><br><br>
  <label for="numpeople">Number of people:</label>
  <input type="text" id="numpeople" name="numpeople"><br><br>
  <input type="submit" value="Submit">
</form>