<!DOCTYPE html>
<html class="no-js" lang="">
<#include "/includes/head.ftlh">
<#include "/includes/preloader.ftlh">
<#include "/includes/header-index.ftlh">

        <!--[if lte IE 9]>
          <p class="browserupgrade">
            You are using an <strong>outdated</strong> browser. Please
            <a href="https://browsehappy.com/">upgrade your browser</a> to improve
            your experience and security.
          </p>
        <![endif]-->

    
        <!-- ========================= hero-section-wrapper-6 end ========================= -->

          <!-- ========================= feature style-5 end ========================= -->
  
        <!-- ========================= gallery style-4 start ========================= -->
        <section id="gallery" class="gallery-section gallery-style-4 bg-white">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-5 col-xl-5 col-lg-7 col-md-10">
                        <div class="section-title text-center mb-60">
                            <h3 class="mb-15 wow fadeInUp" data-wow-delay=".2s">Technologies Used</h3>
                            <p class="wow fadeInUp" data-wow-delay=".4s">Some of the technology used in the development of Planopedia</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="single-gallery wow fadeInUp" data-wow-delay=".2s">
                            <div class="image">
                                <img src="assets/img/gallery/gallery-4/spring-logo.svg" alt="">
                            </div>
                            <div class="info">
                                <h5>Spring Boot</h5>
                                <p>"Spring Boot is Spring's convention-over-configuration solution for creating stand-alone, production-grade Spring-based Applications that you can "just run". It is preconfigured with the Spring team's "opinionated view" of the best configuration and use of the Spring platform and third-party libraries so you can get started with minimum fuss."</p>
                                <ul class="links">
                                    <li><a href="https://en.wikipedia.org/wiki/Spring_Framework#Spring_Boot" target="_new">Wikipedia</a></li>
                                    <li><a href="https://spring.io/projects/spring-boot#overview" target="_new">Project Page</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="single-gallery wow fadeInUp" data-wow-delay=".4s">
                            <div class="image">
                                <img src="assets/img/gallery/gallery-4/mysql-horizontal.svg" alt="">
                            </div>
                            <div class="info">
                                <h5>MySQL</h5>
                                <p>"MySQL is the world's most popular open source database. Whether you are a fast growing web property, technology ISV or large enterprise, MySQL can cost-effectively help you deliver high performance, scalable database applications."</p>
                                <ul class="links">
                                    <li><a href="https://en.wikipedia.org/wiki/MySQL" target="_new">Wikipedia</a></li>
                                    <li><a href="https://www.mysql.com/products/" target="_new">MySQL Product Page</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="single-gallery wow fadeInUp" data-wow-delay=".6s">
                            <div class="image">
                                <img src="assets/img/gallery/gallery-4/yelp_fusion.png" alt="">
                            </div>
                            <div class="info">
                                <h5>Yelp Fusion</h5>
                                <p>The Yelp Fusion API allows you to get the best local content and user reviews from millions of businesses across 32 countries.</p>
                                <ul class="links">
                                    <li><a href="https://www.yelp.com/developers/documentation/v3/get_started" target="_new">Yelp Fusion Docs</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="single-gallery wow fadeInUp" data-wow-delay=".2s">
                            <div class="image">
                                <img src="assets/img/gallery/gallery-4/uideck.svg" alt="">
                            </div>
                            <div class="info">
                                <h5>UIdeck</h5>
                                <p>While a web app's design elements are critical to its usability and adoption rate, there's little programming involved.  So rather than build a UI with the look-and-feel of an early 2000's website, there are many lovely packages available for a nominal cost. UIDeck's Nova template brought a professional yet accessible look to Planopedia! </p>
                                <ul class="links">
                                    <li><a href="https://uideck.com/templates/nova/" target="_new">Nova at UIdeck</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="single-gallery wow fadeInUp" data-wow-delay=".4s">
                            <div class="image">
                                <img src="assets/img/gallery/gallery-4/Google_2015_logo.svg" alt="">
                            </div>
                            <div class="info">
                                <h5>Google Maps and User Login</h5>
                                <p>"Google Maps is a web mapping platform and consumer application offered by Google. It offers satellite imagery, aerial photography, street maps, 360° interactive panoramic views of streets (Street View), real-time traffic conditions, and route planning for traveling by foot, car, air (in beta) and public transportation."</p>
                                <p>"	Google Identity Services is our new cross-platform sign-in SDK for Web and Android apps, supporting and streamlining multiple types of credentials."</p>
                                <ul>
                                	<li><a href="https://en.wikipedia.org/wiki/Google_Maps" target="_new">Google Maps Wikipedia Entry</a></li>
                                	<li><a href="https://developers.google.com/maps/documentation/embed/get-started" target="_new">Get Started with Google Maps</a></li>
                                	<li><a href="https://developers.google.com/identity/gsi/web" target="_new">Google Identity Services</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="single-gallery wow fadeInUp" data-wow-delay=".6s">
                            <div class="image">
                                <img src="assets/img/gallery/gallery-4/OpenWeather-Logo0.svg" alt="">
                            </div>
                            <div class="info">
                                <h5>OpenWeatherMap</h5>
                                <p>"OpenWeatherMap is an online service, owned by OpenWeather Ltd, that provides global weather data via API, including current weather data, forecasts, nowcasts and historical weather data for any geographical location."</p>
                                <ul class="links">
                                  <li><a href="https://en.wikipedia.org/wiki/OpenWeatherMap" target="_new">Wikipedia</a></li>
                                  <li><a href="https://openweathermap.org/" target="_new">OpenWeatherMap</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ========================= gallery style-4 end ========================= -->
      
        <!-- ========================= contact-style-3 start ========================= -->
        <section id="plan" class="contact-section contact-style-3">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-5 col-xl-5 col-lg-7 col-md-10">
                        <div class="section-title text-center mb-50">
                        		<#if plans??>
                        			You have plans!
                        		<#else>
                        			<!--You have no plans!-->
                        		</#if>
                        	
                            		<h3 class="mb-15">Let's Get Started!</h3>
                            
                            <p>Select the type of cuisine you want, number of guests, and Planopedia does the rest!</p>
                            <#if error??>
                                <p style="color:red;">${error}</p>
                            </#if>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="contact-form-wrapper">
                            <form action="/plan/result" method="GET" class="needs-validation">
                                <div class="row justify-content-center">
                                    <div class="col-md-6">
                                        <div class="single-input">
                                          <input type="text" id="name" name="city" class="form-control" placeholder="City" required>                                         
                                        </div>
										<div class="single-input">
                                          <input type="text" id="name" name="zip" class="form-control" placeholder="ZIP" required>
                                        </div>
                                        <div class="single-input">
                                        	<select class="form-select" name="cuisine" required>
                                        				<option selected disabled value	>Cuisine</option>
                                        				<option value="">Any</option>
                                                        <option value="American">American</option>
                                                        <option value="Chinese">Chinese</option>
                                                        <option value="French">French</option>
                                                        <option value="Italian">Italian</option>
                                                        <option value="Jamaican">Jamaican</option>
                                                        <option value="Japanese">Japanese</option>                                                        
                                                        <option value="Mexican">Mexican</option>
                                                        <option value="Mediterranean">Mediterranean</option>
                                             </select>
                                       	</div>
                                        <div class="single-input">
                                            	<select class="form-select" name="numPeople" required>  
                                            			<option selected disabled value>Number of Guests</option>                                          	
                                                        <option value="1">1</option>
                                                        <option value="2">2</option>
                                                        <option value="3">3</option>
                                                        <option value="4">4</option>
                                                        <option value="5">5</option>
                                                        <option value="6">6</option>
                                                        <option value="7">7</option>
                                                        <option value="8">8</option>
                                                        <option value="9">9</option>
                                                    </select>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-button">
                                                <button type="submit" class="button"> <i class="lni lni-telegram-original"></i> Submit</button>
                                            </div>
                                        </div>
                                    </div>
                            </form>
                        </div>

                    </div>

                </div>
        </section>
        <!-- ========================= contact-style-3 end ========================= -->

        <!-- ========================= team style-4 start ========================= -->
        <section id="team" class="team-section team-style-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-5 col-xl-5 col-lg-7 col-md-10">
                        <div class="section-title text-center mb-60">
                            <h3 class="mb-15 wow fadeInUp" data-wow-delay=".2s">Our Team</h3>
                            <p class="wow fadeInUp" data-wow-delay=".4s">As six young college students, we often find it hard to plan out a perfect date. We realize that there are thousands of students across the United States just like us, so by creating this application we hope to ease this problem for not only young college students but everyone out there.</p>
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-xl-3 col-md-6 col-sm-10">
                        <div class="single-team wow fadeInUp" data-wow-delay=".2s">
                            <div class="image">
                                <img src="assets/img/team/team-6/AndyKawabata.jpg" alt="">
                                <div class="overlay">
                                    <ul class="socials">
                                        <li>
                                            <a href="#0"> <i class="lni lni-facebook-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-twitter-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-instagram-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-linkedin-original"></i> </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h6>Andrew Kawabata</h6>
                                <p>Team Member</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-sm-10">
                        <div class="single-team wow fadeInUp" data-wow-delay=".4s">
                            <div class="image">
                                <img src="assets/img/team/team-6/MichaelLeonard.jpg" alt="">
                                <div class="overlay">
                                    <ul class="socials">
                                        <li>
                                            <a href="#0"> <i class="lni lni-facebook-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-twitter-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-instagram-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-linkedin-original"></i> </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h6>Michael Leonard</h6>
                                <p>Team Member</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-sm-10">
                        <div class="single-team wow fadeInUp" data-wow-delay=".6s">
                            <div class="image">
                                <img src="assets/img/team/team-6/DanLuo.jpg" alt="">
                                <div class="overlay">
                                    <ul class="socials">
                                        <li>
                                            <a href="#0"> <i class="lni lni-facebook-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-twitter-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-instagram-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-linkedin-original"></i> </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h6>Dan Luo</h6>
                                <p>Team Member</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-sm-10">
                        <div class="single-team wow fadeInUp" data-wow-delay=".8s">
                            <div class="image">
                                <img src="assets/img/team/team-6/NimraSami.jpg" alt="">
                                <div class="overlay">
                                    <ul class="socials">
                                        <li>
                                            <a href="#0"> <i class="lni lni-facebook-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-twitter-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-instagram-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-linkedin-original"></i> </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h6>Nimra Sami</h6>
                                <p>Team Member</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-sm-10">
                        <div class="single-team wow fadeInUp" data-wow-delay=".8s">
                            <div class="image">
                                <img src="assets/img/team/team-6/ArturoSerdan0.jpg" alt="">
                                <div class="overlay">
                                    <ul class="socials">
                                        <li>
                                            <a href="#0"> <i class="lni lni-facebook-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-twitter-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-instagram-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-linkedin-original"></i> </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h6>Arturo Serdan</h6>
                                <p>Team Member</p>
                            </div>
                        </div>
                    </div>
                                        <div class="col-xl-3 col-md-6 col-sm-10">
                        <div class="single-team wow fadeInUp" data-wow-delay=".8s">
                            <div class="image">
                                <img src="assets/img/team/team-6/JeffWilliams0.jpg" alt="">
                                <div class="overlay">
                                    <ul class="socials">
                                        <li>
                                            <a href="#0"> <i class="lni lni-facebook-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-twitter-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-instagram-filled"></i> </a>
                                        </li>
                                        <li>
                                            <a href="#0"> <i class="lni lni-linkedin-original"></i> </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h6>Jeff Williams</h6>
                                <p>Team Member</p>
                            </div>
                        </div>
                    </div>                    
                </div>

            </div>
        </section>
        <!-- ========================= team style-4 end ========================= -->


        <!-- ========================= testimonial style-4 start ========================= 
        <section id="testimonial" class="testimonial-section testimonial-style-4">
          <div class="container">
            <div class="row">
              <div class="col-lg-12">
                <div class="section-title text-center mb-60">
                  <h3 class="wow fadeInUp" data-wow-delay=".2s">What our clients says?</h3>
                </div>
              </div>
            </div>
    
            <div class="row">
              <div class="col-xl-4 col-md-6">
                <div class="single-testimonial wow fadeInUp" data-wow-delay=".2s">
                  <div class="content-wrapper">
                    <div class="info">
                      <div class="image">
                        <img src="assets/img/testimonial/testimonial-4/testimonial-1.png" alt="">
                      </div>
                      <div class="text">
                        <h6>Sara A.K.</h6>
                        <p>Traveler</p>
                      </div>
                    </div>
                    <div class="content">
                      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leo duis augue commodo neque auctor nisl, libero nunc, egestas. Pellentesque senectus.</p>
                      <div class="quote">
                        <i class="lni lni-quotation"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 col-md-6">
                <div class="single-testimonial wow fadeInUp" data-wow-delay=".4s">
                  <div class="content-wrapper">
                    <div class="info">
                      <div class="image">
                        <img src="assets/img/testimonial/testimonial-4/testimonial-2.png" alt="">
                      </div>
                      <div class="text">
                        <h6>Dev Ed</h6>
                        <p>Frontend Developer</p>
                      </div>
                    </div>
                    <div class="content">
                      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leo duis augue commodo neque auctor nisl, libero nunc, egestas. Pellentesque senectus.</p>
                      <div class="quote">
                        <i class="lni lni-quotation"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-4 col-md-6">
                <div class="single-testimonial wow fadeInUp" data-wow-delay=".6s">
                  <div class="content-wrapper">
                    <div class="info">
                      <div class="image">
                        <img src="assets/img/testimonial/testimonial-4/testimonial-3.png" alt="">
                      </div>
                      <div class="text">
                        <h6>Gray Simon</h6>
                        <p>Programmer</p>
                      </div>
                    </div>
                    <div class="content">
                      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leo duis augue commodo neque auctor nisl, libero nunc, egestas. Pellentesque senectus.</p>
                      <div class="quote">
                        <i class="lni lni-quotation"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
    
          </div>
        </section>
        <!-- ========================= testimonial style-4 end ========================= -->



        <!-- ========================= contact-style-3 start ========================= -->
        <section id="contact" class="contact-section contact-style-3">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xxl-5 col-xl-5 col-lg-7 col-md-10">
                        <div class="section-title text-center mb-50">
                            <h3 class="mb-15">Get in touch</h3>
                            <p>You want to contact the team?  Use this form!</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8">
                        <div class="contact-form-wrapper">
                            <form action="/" method="POST">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="single-input">
                                            <input type="text" id="name" name="name" class="form-input" placeholder="Name">
                                            <i class="lni lni-user"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="single-input">
                                            <input type="email" id="email" name="email" class="form-input" placeholder="Email">
                                            <i class="lni lni-envelope"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="single-input">
                                            <input type="text" id="number" name="number" class="form-input" placeholder="Number">
                                            <i class="lni lni-phone"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="single-input">
                                            <input type="text" id="subject" name="subject" class="form-input" placeholder="Subject">
                                            <i class="lni lni-text-format"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="single-input">
                                            <textarea name="message" id="message" class="form-input" placeholder="Message" rows="6"></textarea>
                                            <i class="lni lni-comments-alt"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-button">
                                            <button type="reset" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" ><i class="lni lni-telegram-original"></i> Submit</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>



                    <div class="col-lg-4">
                        <div class="left-wrapper">
                            <div class="row">
                                <div class="col-lg-12 col-md-6">
                                    <div class="single-item">
                                        <div class="icon">
                                            <i class="lni lni-phone"></i>
                                        </div>
                                        <div class="text">
                                            <p>0045939863784</p>
                                            <p>+004389478327</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-6">
                                    <div class="single-item">
                                        <div class="icon">
                                            <i class="lni lni-envelope"></i>
                                        </div>
                                        <div class="text">
                                            <p>support@planopedia.com</p>
                                            <p>admin@planopedia.com</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-6">
                                    <div class="single-item">
                                        <div class="icon">
                                            <i class="lni lni-map-marker"></i>
                                        </div>
                                        <div class="text">
                                            <p>1 Lodge Street, Asheville, NC 28803, United States</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ========================= contact-style-3 end ========================= -->

        <!-- ========================= clients-logo start ========================= -->
        <section class="clients-logo-section pt-100 pb-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="client-logo wow fadeInUp" data-wow-delay=".2s">
                            <img src="assets/img/clients/brands.svg" alt="" class="w-100">
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ========================= clients-logo end ========================= -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="0" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Email Totally Sent!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Perfect!
        We are absolutely excited to know you've used our contact functionality!  Our Support Staff at /dev/null will proccess your contact in the order it was received!  Expect a response in the amount of time anyone would expect one from /dev/null!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

<#include "/includes/footer.ftlh">
</body>
</html>